theme: jekyll-theme-cayman
title: Human-in-the-loop Chord Progression Generator with Generative Adversarial Network
description: This is the supplementary page for "Human-in-the-loop Chord Progression Generator with Generative Adversarial Network."